#!/usr/bin/env php
<?php
require __DIR__ . '/config/bootstrap.php';

use ARCHphp\CLI\CommandDispatcher;

$commands = require __DIR__ . '/config/commands.php';
$dispatcher = new CommandDispatcher($commands);

$command = $argv[1] ?? '--help';
$args = array_slice($argv, 2);

if ($command === '--help') {
    $dispatcher->showHelp();
    exit;
}

$dispatcher->handle($command, $args);
